### PR TITLE
Add testing and document support for Python 3.9

### PR DESCRIPTION
**Pull request by jdufresne**

### CODE REVIEW

**Comment by ckp95** [comment]
You need to remove the `before_install` section in `travis.yml` to make it succeed, see [this commit](https://github.com/phn/jdcal/pull/28/commits/d562dd3f2872d378d7a9e0e13024f365f860eaf9) in my PR.

**Comment by jdufresne** [comment]
Thanks! I can either wait for that PR or land or #30, whichever makes more sense.

**Comment by jdufresne** [comment]
It looks like the same change is in PR #27.

**Comment by jdufresne** [comment]
rebased

**Comment by phn** [comment]
@jdufresne 

Thanks!

**Pull request merged**
